---
services:
  main:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      # logging
      LOG_LEVEL: "debug"

      AUTHENTICATION_ENABLED: "true"
      API_KEYS: "f791709e0fc2a4eabfdca42a50d905a8"

      DRAGONFLY_HOST: "dragonfly"

      # metrics
      METRICS_ENABLED: "true"
      METRICS_PORT: "8081"

      # tracing
      TRACING_ENABLED: "false"
      TRACING_SAMPLERATE: "1.0"
      TRACING_SERVICE: "lfpweather-forecast-inference-api"
      TRACING_VERSION: "0.0.1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"

      # grpc (otlp tracing)
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
    depends_on:
      dragonfly:
        condition: service_started

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml
      - /tmp/tempo-data:/tmp/tempo
    ports:
      - "4317:4317" #  otlp grpc
      - "4318:4318" #  otlp http

  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
